### ISSUE TITLE
Issue with JsonToGo on Nvim

### ISSUE THREAD

**Issue by ASoldo** [meain/vim-jsontogo#1]
Hi, I just found out about this ability to convert json to go, but I have issue when I run it as you explained in NORMAL mode while selecting json.

![image](https://github.com/user-attachments/assets/cf745df0-d9d0-4682-aacb-52ac4a0eadb1)
![image](https://github.com/user-attachments/assets/9209eb26-4b80-4c92-9142-64d0769c5308)
![image](https://github.com/user-attachments/assets/a346128a-e514-4077-9508-9392e00ac84b)

Do you know how can I resolve this? Thank you!

**Comment by meain** [comment]
This is likely due to the json being invalid, in this case there should not be a comma after 34. In json, the last entry should not end with a comma.

BTW, this plugin is kinda unnecessary. I built this when I didn't know any better. You can just select the text an call `:!gojson` and it will do the same thing. This plugin is just a wrapper on the gojson tool and you can use that directly instead if you prefer.

In vim, selecting a piece of text and calling `:!<cmd>` (if you have a selection when hitting `:`, then the it will act on the selection) will pass the text to the stdin of the command and drop the stdout/stderr of that to the buffer.
Ref: https://vimways.org/2019/vim-and-the-shell/

**Comment by ASoldo** [comment]
I see, thank you for clarification. It works now with !gojson.
